name: alphafix
description: Fix camera video metadata using ExifTool.
publish_to: 'none'
version: 1.0.0+1
# AlphaFix — Metadata Repair Tool. Developed by Meghana.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  desktop_drop: ^0.4.4
  path: ^1.9.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo.svg

flutter_launcher_icons:
  image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"
